name: Deploy to Nekoweb

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: "deploy"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: nekoweb
      url: 'https://inaccessible.nekoweb.org'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build inaccessible
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
          NEKOWEB_APIKEY: ${{ secrets.NEKOWEB_APIKEY }}
          NEKOWEB_COOKIE: ${{ secrets.NEKOWEB_COOKIE }}
        run: bun run build
